apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wayback-archive
  description: Archive of the wayback machine
spec:
  type: service
  lifecycle: production
  owner: archive@example.com
  providesApis:
    - wayback-archive
